BulkyWeb/Models/Category.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BulkyWeb.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [MaxLength(30)]
        [DisplayName("Category Name")]
        public string Name { get; set; }
        [DisplayName("Display Order")]
        [Range(1,100,ErrorMessage ="Order must be between 1-100")]
        public int DisplayOrder { get; set; }
    }
}

BulkyWeb/Models/ErrorViewModel.cs
namespace BulkyWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BulkyWeb/Controllers/CategoryController.cs
using Bulky.DataAccess.Data;
using Bulky.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyWeb.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            List<Category> objCategoryList = _db.Categories.ToList();
            return View(objCategoryList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category obj)
        {
            if(obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "The name and order can't be same");
            }
            if (ModelState.IsValid)
            {
                _db.Categories.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Category created successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if(id==null || id == 0)
            {
                return NotFound();
            }
            Category? categoryFromDb = _db.Categories.Find(id);//only work for primary key..
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }
        [HttpPost]
        public IActionResult Edit(Category obj)
        {
            if (ModelState.IsValid)
            {
                _db.Categories.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? categoryFromDb = _db.Categories.Find(id);//only work for primary key..
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }
        [HttpPost,ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Category? obj = _db.Categories.Find(id);
            if(obj == null)
            {
                return NotFound();
            }
            _db.Categories.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

BulkyWeb/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Bulky.Models;

namespace BulkyWeb.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

BulkyWeb/Views/Category/Create.cshtml
@model Category

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Create Category</h2> 
			<hr/>
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3" row> 
			<label asp-for="Name"></label>
			<input asp-for="Name" class="form-control"/>
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<div class="mb-3" row>
			<label asp-for="DisplayOrder"></label>
			<input asp-for="DisplayOrder" type="text" class="form-control" />
			<span asp-validation-for="DisplayOrder" class="text-danger"></span>
		</div>
		<div class="row">
			<div class="col-6 col-md-3">
				<button type="submit" class="btn btn-primary form-control">Create</button>
			</div>
			<div class="col-6 col-md-3">
				<a asp-controller="Category" asp-action="Index" class="btn btn-secondary border form-control">
					Back to List
				</a>
			</div>
		</div>
		
		
	</div>

</form>
@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial"/>
	}
}

BulkyWeb/Views/Category/Delete.cshtml
@model Category

<form method="post">
	<input asp-for="Id" hidden/>
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Delete Category</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3" row>
			<label asp-for="Name"></label>
			<input asp-for="Name" disabled class="form-control" />
			
		</div>
		<div class="mb-3" row>
			<label asp-for="DisplayOrder"></label>
			<input asp-for="DisplayOrder" type="text" disabled class="form-control" />
		</div>
		<div class="row">
			<div class="col-6 col-md-3">
				<button type="submit" class="btn btn-danger form-control">Delete</button>
			</div>
			<div class="col-6 col-md-3">
				<a asp-controller="Category" asp-action="Index" class="btn btn-secondary border form-control">
					Back to List
				</a>
			</div>
		</div>


	</div>

</form>
@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

BulkyWeb/Views/Category/Edit.cshtml
@model Category

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Edit Category</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3" row>
			<label asp-for="Name"></label>
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<div class="mb-3" row>
			<label asp-for="DisplayOrder"></label>
			<input asp-for="DisplayOrder" type="text" class="form-control" />
			<span asp-validation-for="DisplayOrder" class="text-danger"></span>
		</div>
		<div class="row">
			<div class="col-6 col-md-3">
				<button type="submit" class="btn btn-primary form-control">Update</button>
			</div>
			<div class="col-6 col-md-3">
				<a asp-controller="Category" asp-action="Index" class="btn btn-secondary border form-control">
					Back to List
				</a>
			</div>
		</div>


	</div>

</form>
@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

BulkyWeb/Views/Category/Index.cshtml
@model List<Category>     

<div class=" container">
    <div class="row pt-4 pb-3">
        <div class="col-6">
            <h2 class="text-primary">
                Category List
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Category" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i>Create New Category
            </a>
        </div>
    </div>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <td>
                Category Name
            </td>
            <th>
                Display Order
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model.OrderBy(u=>u.DisplayOrder))
        {
            <tr>
                <td>@obj.Name</td>
                <td>@obj.DisplayOrder</td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Category" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                                <i class="bi bi-pencil-square"></i>Edit
                        </a>
                            <a asp-controller="Category" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                                <i class="bi bi-trash-fill"></i>Delete
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>

BulkyWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BulkyWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyWeb</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BulkyWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BulkyWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container">
            Made with <i class="bi bi-heart-fill"></i> by DotNetMastery
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}